# Generated by Django 3.0.3 on 2020-04-21 19:11

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to=post.models.get_upload_path),
        ),
    ]
