# Generated by Django 3.0.3 on 2020-04-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200421_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.CharField(default='Montreal', max_length=1000),
            preserve_default=False,
        ),
    ]
