# Generated by Django 3.0.3 on 2020-04-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_history_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
